version: "3.2"
networks:
  atos-net:
    driver: bridge
services:
  atos:
    image: astazero/atos_docker_env:test
    networks:
      - atos-net
    volumes: 
      - ./conf/Catalogs/:/root/.astazero/ATOS/Catalogs
      - ./conf/conf/:/root/.astazero/ATOS/conf
      - ./conf/objects/:/root/.astazero/ATOS/objects
      - ./conf/odr/:/root/.astazero/ATOS/odr
      - ./conf/osc/:/root/.astazero/ATOS/osc
    command: bash -c "source /root/atos_ws/install/setup.sh ; python3 -m pytest /root/atos_ws/src/atos/scripts/integration_testing/run_scenario_test.py"
  isoObject:
    image: astazero/iso_object_demo:latest
    networks:
      - atos-net