atos:
  journal_control:
    ros__parameters:
      scenario_name: ""
  esmini_adapter:
    ros__parameters:
      open_scenario_file: "GaragePlanScenario.xosc"
  object_control:
    ros__parameters:
      max_missing_heartbeats: 100
      transmitter_id: 15
  osi_adapter:
    ros__parameters:
      address: "0.0.0.0"
      port: 55555
      protocol: "tcp"
      frequency: 100
  mqtt_bridge:
    ros__parameters:
      broker_ip: ""
      port: 1883
      client_id: ""
      username: ""
      password: ""
      topic: ""
      quality_of_service: 1
  trajectorylet_streamer:
    ros__parameters:
      chunk_duration: 2.0
  pointcloud_publisher:
    ros__parameters:
      pointcloud_files: [""]
  integration_testing_handler:
    ros__parameters:
      scenario_execution: true
  back_to_start:
    ros__parameters:
      turn_radius: 5.0
      min_speed: 4.0
      max_speed: 12.0