name: Build ATOS from source

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: foxy

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.3.3
      with:
        package-name: atos

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()